# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
    - python: 3.5

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh -O anaconda.sh;
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install python=3.6 lawrap cmake mkl-include gcc-5-mp bzip2 pybind11 -c conda-forge -c intel -c anaconda
  - pip install codecov
  - conda list

before_script:
  - python -V

script:
  - pip install -e .
  - py.test -v --cov=./

after_success:
  - codecov

notifications:
  email: false
